#!/bin/bash
# rebuild-manifest.sh — Regenerates memories/manifest.md from entry frontmatter
# Runs during weekly consolidation or on demand
# Extracts: filename, type(subtype), domain, importance, keywords, first body line (summary)

ENTRIES_DIR="/c/Users/kurtw/.claudia/memories/entries"
MANIFEST="/c/Users/kurtw/.claudia/memories/manifest.md"

echo "# Memory Manifest" > "$MANIFEST"
echo "_Auto-generated index. Read this instead of opening files. Regenerated by rebuild-manifest.sh._" >> "$MANIFEST"
echo "" >> "$MANIFEST"

for f in "$ENTRIES_DIR"/*.md; do
  [ -f "$f" ] || continue
  fname=$(basename "$f" .md)

  # Extract frontmatter fields
  type=$(sed -n '/^---$/,/^---$/{ /^type:/{ s/type: *//; p; q; } }' "$f")
  subtype=$(sed -n '/^---$/,/^---$/{ /^subtype:/{ s/subtype: *//; p; q; } }' "$f")
  domain=$(sed -n '/^---$/,/^---$/{ /^domain:/{ s/domain: *//; p; q; } }' "$f")
  importance=$(sed -n '/^---$/,/^---$/{ /^importance:/{ s/importance: *//; p; q; } }' "$f")
  keywords=$(sed -n '/^---$/,/^---$/{ /^keywords:/{ s/keywords: *//; p; q; } }' "$f")

  # Build type label
  if [ -n "$subtype" ]; then
    typelabel="${subtype}"
  else
    typelabel="${type:-unknown}"
  fi

  # Extract first non-empty, non-heading line after second ---
  summary=$(awk '
    /^---$/ { count++; next }
    count >= 2 && /^[^#\s]/ && NF > 0 { print; exit }
    count >= 2 && /^##? / { next }
  ' "$f" | head -c 120)

  # Format manifest line
  line="- \`${fname}\` [${typelabel}/${domain:-?}/${importance:-?}]"
  if [ -n "$summary" ]; then
    line="${line} — ${summary}"
  fi
  if [ -n "$keywords" ]; then
    line="${line} | ${keywords}"
  fi

  echo "$line" >> "$MANIFEST"
done

count=$(grep -c '^\- ' "$MANIFEST")
echo ""  >> "$MANIFEST"
echo "_${count} entries indexed._" >> "$MANIFEST"
