#!/usr/bin/env node
// research-digest.mjs — Search for fresh news, generate draft tweets
// Usage: node research-digest.mjs [--topics "ai agents,crypto,saas"] [--output drafts.md]
//        node research-digest.mjs --dry-run  # Show what would be searched
//
// Searches Firecrawl for today's news on configured topics, scrapes top results,
// extracts key data points, and outputs draft tweets ready for reply-session.mjs.
// No Chrome needed — runs entirely on Firecrawl + local processing.

import { execSync } from 'child_process';
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { join } from 'path';

const HOME = process.env.HOME || process.env.USERPROFILE || 'C:/Users/kurtw';
const FIRECRAWL_DIR = join(HOME, '.claudia', '.firecrawl');
const DRAFTS_DIR = join(HOME, '.claudia', 'schedule', 'initiatives', 'grow-twitter');

const DEFAULT_TOPICS = [
  { query: 'AI agent economy crypto 2026', tag: 'agent-economy' },
  { query: 'Claude Code anthropic agentic', tag: 'claude-code' },
  { query: 'SaaS AI disruption seat compression', tag: 'saas-unbundling' },
  { query: 'pump.fun tokenized agents Solana', tag: 'pumpfun' },
  { query: 'AI agent payments x402 stablecoin', tag: 'agent-payments' },
  { query: 'MCP model context protocol tools', tag: 'mcp' },
  { query: 'prediction market AI arbitrage DeFAI', tag: 'prediction-markets' },
];

const args = process.argv.slice(2);
const dryRun = args.includes('--dry-run');
const topicsArg = args.find(a => a.startsWith('--topics='));
const outputArg = args.find(a => a.startsWith('--output='));

const today = new Date().toLocaleDateString('en-CA'); // YYYY-MM-DD local
const outputFile = outputArg?.split('=')[1] || join(DRAFTS_DIR, `drafts-${today}-digest.md`);

let topics = DEFAULT_TOPICS;
if (topicsArg) {
  topics = topicsArg.split('=')[1].split(',').map(t => ({
    query: t.trim(),
    tag: t.trim().replace(/\s+/g, '-').toLowerCase().substring(0, 20)
  }));
}

function firecrawlSearch(query, limit = 5) {
  const outFile = join(FIRECRAWL_DIR, `search-digest-${query.replace(/\s+/g, '_').substring(0, 30)}.json`);
  try {
    execSync(
      `firecrawl search "${query}" --tbs qdr:d --limit ${limit} -o "${outFile}" --json`,
      { encoding: 'utf8', timeout: 30000, stdio: ['pipe', 'pipe', 'pipe'] }
    );
    if (existsSync(outFile)) {
      const data = JSON.parse(readFileSync(outFile, 'utf8'));
      return (data.data?.web || data.data || []).map(r => ({
        title: r.title,
        url: r.url,
        description: r.description || ''
      }));
    }
  } catch (e) {
    console.error(`  Search failed for "${query}": ${e.message?.substring(0, 100)}`);
  }
  return [];
}

function extractDataPoints(results) {
  const points = [];
  for (const r of results) {
    // Look for numbers, percentages, dollar amounts in descriptions
    const nums = r.description.match(/\$[\d,.]+[BMK]?|\d+%|\d+[,.]\d+\s*(billion|million|thousand)/gi) || [];
    if (nums.length > 0) {
      points.push({ source: r.title, url: r.url, data: nums.join(', '), desc: r.description });
    } else if (r.description.length > 50) {
      points.push({ source: r.title, url: r.url, data: null, desc: r.description });
    }
  }
  return points;
}

function generateDraftSection(tag, results, points) {
  let section = `## ${tag}\n_Sources: ${results.length} results found_\n\n`;

  if (results.length === 0) {
    section += `_No fresh results today._\n\n`;
    return section;
  }

  // List sources
  for (const r of results.slice(0, 3)) {
    section += `- [${r.title}](${r.url})\n`;
  }
  section += '\n';

  // Data points for draft inspiration
  if (points.length > 0) {
    section += '### Data points for drafts\n';
    for (const p of points.slice(0, 3)) {
      section += `- ${p.data || 'qualitative'}: ${p.desc.substring(0, 150)}\n`;
      section += `  Source: ${p.source}\n`;
    }
    section += '\n';
  }

  section += `### Draft angles\n`;
  section += `_Write 1-2 reply drafts per angle. Target: under 280 chars, data-led, opinion at the end._\n\n`;

  return section;
}

// Main
console.log(`Research Digest — ${today}`);
console.log(`Topics: ${topics.length}`);
console.log(`Output: ${outputFile}\n`);

if (dryRun) {
  console.log('DRY RUN — would search:');
  for (const t of topics) {
    console.log(`  [${t.tag}] "${t.query}"`);
  }
  process.exit(0);
}

if (!existsSync(FIRECRAWL_DIR)) mkdirSync(FIRECRAWL_DIR, { recursive: true });

let markdown = `# Research Digest — ${today}\n`;
markdown += `_Auto-generated by research-digest.mjs. Use data points to write reply drafts._\n`;
markdown += `_Search: Firecrawl, past 24h, ${topics.length} topics._\n\n`;

let totalResults = 0;
let totalPoints = 0;

for (const topic of topics) {
  process.stdout.write(`Searching: [${topic.tag}] `);
  const results = firecrawlSearch(topic.query);
  const points = extractDataPoints(results);
  totalResults += results.length;
  totalPoints += points.length;
  console.log(`${results.length} results, ${points.length} data points`);

  markdown += generateDraftSection(topic.tag, results, points);
}

markdown += `---\n## Summary\n`;
markdown += `- ${totalResults} total results across ${topics.length} topics\n`;
markdown += `- ${totalPoints} data points extracted\n`;
markdown += `- Generated: ${new Date().toISOString()}\n`;

writeFileSync(outputFile, markdown);
console.log(`\nDigest written to: ${outputFile}`);
console.log(`${totalResults} results, ${totalPoints} data points across ${topics.length} topics`);
